name: Arvella
favicon: null
layout_spectrum: 0.49275
typography_spectrum: 0.89511
title: Arvella
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b1afae'
    - '#c00027'
    - '#000000'
    - '#ffffff'
    - '#808080'
  brandStrength: 0.5
  lightness: 0.3103348151780665
  saturation: 0.9245113225188106
  rhythmicContrast: 0.46609907085075974
purpose: []
