name: Arvella
favicon: null
layout_spectrum: 0
typography_spectrum: 0.89511
title: Arvella
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b1afae'
    - '#c00027'
    - '#000000'
    - '#ffffff'
    - '#808080'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
