name: Arvella
favicon: null
layout_spectrum: 0.002796519547700882
typography_spectrum: 0.0698836522642523
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.7352095791138709
  lightness: 0.3103348151780665
  saturation: 0.9245113225188106
  rhythmicContrast: 0.46609907085075974
purpose: []
